try again

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -15,156 +15,156 @@
 
 name: Kybra Tests
 on:
-  push:
-    branches:
-      - main
-  pull_request: # Runs on pull requests to any branch
+    push:
+        branches:
+            - main
+    pull_request: # Runs on pull requests to any branch
 jobs:
-  release-candidate-deploy:
-    runs-on: ubuntu-latest
-    env:
-      GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }} # All commits must be verified
-    outputs:
-      # These outputs are used to pass information along to the next job
-      should_run_tests: ${{ steps.should_run_tests.outputs.should_run_tests }} # We only want the next job to run the tests once we have finished deploying to PyPI and GitHub
-      example_directories: ${{ steps.example_directories.outputs.example_directories }}
-    steps:
-      - uses: actions/checkout@v2
-        # if: contains(github.head_ref, 'release--')
-        with:
-          ref: ${{ contains(github.head_ref, 'release--') && github.event.pull_request.head.ref || github.ref }} # This is necessary for this job to be able to commit and push to the origin remote properly
-          token: ${{ secrets.LASTMJS_GITHUB_TOKEN || github.token }} # A personal GitHub token is setup as a secret so that committing and pushing to GitHub from the Action will trigger another workflow
-      - uses: actions/setup-node@v3
-        with:
-          node-version: 18
-          registry-url: https://registry.npmjs.org
+    release-candidate-deploy:
+        runs-on: ubuntu-latest
         env:
-          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # TODO this will need to be the PyPI auth token
-      # TODO we should use some Action-specific bot account
-      - if: contains(github.head_ref, 'release--')
-        run: git config --global user.name 'Jordan Last'
-      - if: contains(github.head_ref, 'release--')
-        run: git config --global user.email 'jordan.michael.last@gmail.com'
-      - if: contains(github.head_ref, 'release--')
-        run: git config --global commit.gpgsign true
-      - if: contains(github.head_ref, 'release--')
-        run: echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
-      - if: contains(github.head_ref, 'release--')
-        run: git config --global user.signingkey C8B77BCBE16CD2B94B43F9C8757397B82D4ED7B0
-      - id: example_directories
-        # TODO to improve this further we might be able to create an environment variable that grabs the example directories with a glob
-        # TODO we want to be able to easily include and exclude examples though
-        run: |
-          EXAMPLE_DIRECTORIES=$(cat << END
-          [
-            "examples/query"
-          ]
-          END
-          )
-          EXAMPLE_DIRECTORIES="${EXAMPLE_DIRECTORIES//'%'/'%25'}"
-          EXAMPLE_DIRECTORIES="${EXAMPLE_DIRECTORIES//$'\n'/'%0A'}"
-          EXAMPLE_DIRECTORIES="${EXAMPLE_DIRECTORIES//$'\r'/'%0D'}"
-          echo "::set-output name=example_directories::$EXAMPLE_DIRECTORIES"
-      - id: should_run_tests
-        run: |
-          BRANCH_NAME="${{ github.head_ref }}"
-          RELEASE_VERSION="${BRANCH_NAME:9}"
-          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
-          if [[ "${{ contains(github.head_ref, 'release--') }}" == "true" && "$COMMIT_MESSAGE" != "kybra-bot automated release $RELEASE_VERSION" ]]
-          then
-            ./publish-github-action.sh $RELEASE_VERSION ${{ toJSON(steps.example_directories.outputs.example_directories) }}
-          else
-            echo "::set-output name=should_run_tests::true"
-          fi
-  basic-integration-tests:
-    needs: release-candidate-deploy
-    runs-on: ubuntu-latest
-    env:
-      ETHEREUM_URL: ${{ secrets.ETHEREUM_URL }}
-    strategy:
-      fail-fast: false # We want to see which example tests succeed and which ones fail, we don't want one example test to cancel the rest
-      matrix:
-        # TODO perhaps we should start testing on different versions of dfx as well
-        rust: [stable]
-        include_pypi:
-          # Only include pypi in the matrix if you've pushed to main and the last commit was a merge of a release branch, or the base branch of the pull request is a release branch
-          - ${{ (github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'Merge pull request') && contains(github.event.head_commit.message, 'demergent-labs/release--')) || contains(github.head_ref, 'release--') }}
-        kybra_source:
-          - pypi
-          - repo
-        exclude:
-          - include_pypi: false
-            kybra_source: pypi
-        # If should_run_tests is false, we still want the steps of this job to execute so that check-basic-integration-tests-success will run. We do this by creating an array with one dummy element
-        example_directories: ${{ needs.release-candidate-deploy.outputs.should_run_tests == 'true' && fromJSON(needs.release-candidate-deploy.outputs.example_directories) || fromJSON('["dummy"]') }}
-    steps:
-      - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
-        uses: actions/checkout@v2
-      - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
-        uses: actions/setup-node@v3
-        with:
-          node-version: 18
-      - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
-        run: DFX_VERSION=0.12.0-beta.3 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
-      - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
-        name: Install Rust ${{ matrix.rust }}
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: ${{ matrix.rust }}
-          profile: minimal
-          override: true
-      - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
-        uses: actions/cache@v3
-        with:
-          path: |
-            ~/.cargo/bin/
-            ~/.cargo/registry/index/
-            ~/.cargo/registry/cache/
-            ~/.cargo/git/db/
-            ${{ matrix.example_directories }}/target/
-          key: kybra-cargo-${{ matrix.example_directories }}-${{ matrix.kybra_source }}-${{ hashFiles('kybra/compiler/Cargo.toml') }}
-      - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
-        working-directory: ${{ matrix.example_directories }}
-        run: curl https://pyenv.run | bash
-      - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
-        working-directory: ${{ matrix.example_directories }}
-        run: ~/.pyenv/bin/pyenv install 3.10.7
-      - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
-        working-directory: ${{ matrix.example_directories }}
-        run: ~/.pyenv/versions/3.10.7/bin/python -m venv .dfx/kybra/venv
-      - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
-        working-directory: ${{ matrix.example_directories }}
-        run: source .dfx/kybra/venv/bin/activate
-      - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
-        working-directory: ${{ matrix.example_directories }}
-        run: REPLICA_PORT=8000 dfx start --clean --background --enable-canister-http
-      - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests && matrix.kybra_source == 'repo' }}
-        shell: bash -l {0}
-        working-directory: ${{ matrix.example_directories }}
-        run: pip install ../..
-      - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests && matrix.kybra_source == 'pypi' }}
-        shell: bash -l {0}
-        working-directory: ${{ matrix.example_directories }}
-        run: pip install kybra # TODO this should really be a locked-down version...we probably need requirements.txt or something
-      - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
-        shell: bash -l {0}
-        working-directory: ${{ matrix.example_directories }}/test
-        run: npm install
-      - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
-        shell: bash -l {0}
-        working-directory: ${{ matrix.example_directories }}/test
-        run: npm test
+            GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }} # All commits must be verified
+        outputs:
+            # These outputs are used to pass information along to the next job
+            should_run_tests: ${{ steps.should_run_tests.outputs.should_run_tests }} # We only want the next job to run the tests once we have finished deploying to PyPI and GitHub
+            example_directories: ${{ steps.example_directories.outputs.example_directories }}
+        steps:
+            - uses: actions/checkout@v2
+              # if: contains(github.head_ref, 'release--')
+              with:
+                  ref: ${{ contains(github.head_ref, 'release--') && github.event.pull_request.head.ref || github.ref }} # This is necessary for this job to be able to commit and push to the origin remote properly
+                  token: ${{ secrets.LASTMJS_GITHUB_TOKEN || github.token }} # A personal GitHub token is setup as a secret so that committing and pushing to GitHub from the Action will trigger another workflow
+            - uses: actions/setup-node@v3
+              with:
+                  node-version: 18
+                  registry-url: https://registry.npmjs.org
+              env:
+                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # TODO this will need to be the PyPI auth token
+            # TODO we should use some Action-specific bot account
+            - if: contains(github.head_ref, 'release--')
+              run: git config --global user.name 'Jordan Last'
+            - if: contains(github.head_ref, 'release--')
+              run: git config --global user.email 'jordan.michael.last@gmail.com'
+            - if: contains(github.head_ref, 'release--')
+              run: git config --global commit.gpgsign true
+            - if: contains(github.head_ref, 'release--')
+              run: echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
+            - if: contains(github.head_ref, 'release--')
+              run: git config --global user.signingkey C8B77BCBE16CD2B94B43F9C8757397B82D4ED7B0
+            - id: example_directories
+              # TODO to improve this further we might be able to create an environment variable that grabs the example directories with a glob
+              # TODO we want to be able to easily include and exclude examples though
+              run: |
+                  EXAMPLE_DIRECTORIES=$(cat << END
+                  [
+                    "examples/query"
+                  ]
+                  END
+                  )
+                  EXAMPLE_DIRECTORIES="${EXAMPLE_DIRECTORIES//'%'/'%25'}"
+                  EXAMPLE_DIRECTORIES="${EXAMPLE_DIRECTORIES//$'\n'/'%0A'}"
+                  EXAMPLE_DIRECTORIES="${EXAMPLE_DIRECTORIES//$'\r'/'%0D'}"
+                  echo "::set-output name=example_directories::$EXAMPLE_DIRECTORIES"
+            - id: should_run_tests
+              run: |
+                  BRANCH_NAME="${{ github.head_ref }}"
+                  RELEASE_VERSION="${BRANCH_NAME:9}"
+                  COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
+                  if [[ "${{ contains(github.head_ref, 'release--') }}" == "true" && "$COMMIT_MESSAGE" != "kybra-bot automated release $RELEASE_VERSION" ]]
+                  then
+                    ./publish-github-action.sh $RELEASE_VERSION ${{ toJSON(steps.example_directories.outputs.example_directories) }}
+                  else
+                    echo "::set-output name=should_run_tests::true"
+                  fi
+    basic-integration-tests:
+        needs: release-candidate-deploy
+        runs-on: ubuntu-latest
+        env:
+            ETHEREUM_URL: ${{ secrets.ETHEREUM_URL }}
+        strategy:
+            fail-fast: false # We want to see which example tests succeed and which ones fail, we don't want one example test to cancel the rest
+            matrix:
+                # TODO perhaps we should start testing on different versions of dfx as well
+                rust: [stable]
+                include_pypi:
+                    # Only include pypi in the matrix if you've pushed to main and the last commit was a merge of a release branch, or the base branch of the pull request is a release branch
+                    - ${{ (github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, 'Merge pull request') && contains(github.event.head_commit.message, 'demergent-labs/release--')) || contains(github.head_ref, 'release--') }}
+                kybra_source:
+                    - pypi
+                    - repo
+                exclude:
+                    - include_pypi: false
+                      kybra_source: pypi
+                # If should_run_tests is false, we still want the steps of this job to execute so that check-basic-integration-tests-success will run. We do this by creating an array with one dummy element
+                example_directories: ${{ needs.release-candidate-deploy.outputs.should_run_tests == 'true' && fromJSON(needs.release-candidate-deploy.outputs.example_directories) || fromJSON('["dummy"]') }}
+        steps:
+            - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
+              uses: actions/checkout@v2
+            - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
+              uses: actions/setup-node@v3
+              with:
+                  node-version: 18
+            - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
+              run: DFX_VERSION=0.12.0-beta.3 sh -ci "$(curl -fsSL https://sdk.dfinity.org/install.sh)"
+            - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
+              name: Install Rust ${{ matrix.rust }}
+              uses: actions-rs/toolchain@v1
+              with:
+                  toolchain: ${{ matrix.rust }}
+                  profile: minimal
+                  override: true
+            - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
+              uses: actions/cache@v3
+              with:
+                  path: |
+                      ~/.cargo/bin/
+                      ~/.cargo/registry/index/
+                      ~/.cargo/registry/cache/
+                      ~/.cargo/git/db/
+                      ${{ matrix.example_directories }}/target/
+                  key: kybra-cargo-${{ matrix.example_directories }}-${{ matrix.kybra_source }}-${{ hashFiles('kybra/compiler/Cargo.toml') }}
+            - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
+              working-directory: ${{ matrix.example_directories }}
+              run: curl https://pyenv.run | bash
+            - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
+              working-directory: ${{ matrix.example_directories }}
+              run: ~/.pyenv/bin/pyenv install 3.10.7
+            - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
+              working-directory: ${{ matrix.example_directories }}
+              run: ~/.pyenv/versions/3.10.7/bin/python -m venv .dfx/kybra/venv
+            - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
+              working-directory: ${{ matrix.example_directories }}
+              run: source .dfx/kybra/venv/bin/activate
+            - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
+              working-directory: ${{ matrix.example_directories }}
+              run: dfx start --clean --background --enable-canister-http
+            - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests && matrix.kybra_source == 'repo' }}
+              shell: bash -l {0}
+              working-directory: ${{ matrix.example_directories }}
+              run: pip install ../..
+            - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests && matrix.kybra_source == 'pypi' }}
+              shell: bash -l {0}
+              working-directory: ${{ matrix.example_directories }}
+              run: pip install kybra # TODO this should really be a locked-down version...we probably need requirements.txt or something
+            - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
+              shell: bash -l {0}
+              working-directory: ${{ matrix.example_directories }}/test
+              run: npm install
+            - if: ${{ needs.release-candidate-deploy.outputs.should_run_tests }}
+              shell: bash -l {0}
+              working-directory: ${{ matrix.example_directories }}/test
+              run: npm test
 
-  check-basic-integration-tests-success:
-    needs: basic-integration-tests
-    runs-on: ubuntu-latest
-    if: success()
-    steps:
-      - run: exit 0
+    check-basic-integration-tests-success:
+        needs: basic-integration-tests
+        runs-on: ubuntu-latest
+        if: success()
+        steps:
+            - run: exit 0
 
-  check-basic-integration-tests-failure:
-    needs: basic-integration-tests
-    runs-on: ubuntu-latest
-    if: failure()
-    steps:
-      - run: exit 1
+    check-basic-integration-tests-failure:
+        needs: basic-integration-tests
+        runs-on: ubuntu-latest
+        if: failure()
+        steps:
+            - run: exit 1
